name: tomvonderisar
favicon: null
layout_spectrum: 0.01445
typography_spectrum: 0.40173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7477054921910167
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
