name: Tom von der Isar
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43064
title: Tom von der Isar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7a0f05'
    - '#c19882'
    - '#83604a'
    - '#f12a17'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
