name: tomvonderisar
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#dcd0d2'
    - '#b7a5a5'
    - '#4f2c1a'
    - '#8f5e48'
  brandStrength: 0.7477054921910167
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
